#!/bin/bash
# Script to configure system to use local DNS

echo "Configuring system to use local Pi-hole DNS..."

# Create NetworkManager config to use local DNS
sudo tee /etc/NetworkManager/conf.d/dns-servers.conf > /dev/null <<EOF
[main]
dns=none

[global-dns-domain-*]
servers=127.0.0.1
EOF

# Update resolv.conf
sudo tee /etc/resolv.conf > /dev/null <<EOF
# Generated by security-stack
nameserver 127.0.0.1
EOF

# Make resolv.conf immutable so NetworkManager doesn't overwrite it
sudo chattr +i /etc/resolv.conf

# Restart NetworkManager
sudo systemctl restart NetworkManager

echo "DNS configured! Testing..."
dig @127.0.0.1 google.com +short

echo "Done! Your system now uses Pi-hole for all DNS queries."
